services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          property: host
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          property: hostport
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_ENCRYPTION_KEY
        value: 2193f93c83e52f739f585587b0fb1d40a68f501b106691f4a87ef6b06d1cd5ec
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false